# PayPal Donate Plugin Configuration

paypaldonateClientId = ""
paypaldonateSecret = ""
paypaldonateCurrency = "USD"
paypaldonateMode = "sandbox"

paypaldonateMinAmount = "1"
paypaldonateMaxAmount = "1000"
