# Datenstrom Yellow extension settings

Extension: paypaldonate
Version: 0.1
Description: paypal payment integration through paypal API 
Developer: Mao-urban
Tag: payments, feature, paypal
DownloadUrl: https://github.com/Mao-urban/paypal-yellow/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/Mao-urban/paypal-yellow
Published: 2026-03-23 18:00:30
Status: experimental
system/workers/paypaldonate.php: paypaldonate.php, create, update
PaypaldonateClientId = ""
PaypaldonateSecret = ""
PaypaldonateCurrency = "USD"
PaypaldonateMode = "sandbox"
PaypaldonateMinAmount = "1"
PaypaldonateMaxAmount = "1000"
